# Generated by Django 5.2 on 2025-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='storage',
            field=models.CharField(choices=[('Supply Room', 'Supply Room'), ('Cold Storage', 'Cold Storage'), ('Meat & Poultry', 'Meat & Poultry')], default='Supply Room', max_length=50),
        ),
    ]
