# Generated by Django 5.2 on 2025-04-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_rawmaterial_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='minimum_stock_level',
            field=models.FloatField(default=0),
        ),
    ]
