# Generated by Django 5.2 on 2025-04-26 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_rawmaterial_minimum_stock_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opening_stock', models.FloatField()),
                ('closing_stock', models.FloatField()),
                ('used_stock', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('current_stock', models.FloatField()),
                ('minimum_stock_level', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.rawmaterial')),
            ],
        ),
    ]
