# Generated by Django 5.2 on 2025-04-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_dailyreport_remove_dailystockreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystockreport',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stock_reports', to='restaurant.dailyreport'),
        ),
    ]
