# Generated by Django 5.2 on 2025-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_dailystockreport_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='storage',
            field=models.CharField(choices=[('Stock Room', 'Stock Room'), ('Cold Storage', 'Cold Storage')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
