# Generated by Django 5.2 on 2025-04-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_dailyreport_storage_alter_dailyreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='storage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
