# Generated by Django 5.2 on 2025-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_dailyreport_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('date', 'storage')},
        ),
    ]
